FROM python:3.11-alpine

RUN wget https://dl.min.io/client/mc/release/linux-amd64/mc -O /usr/local/bin/mc && chmod +x /usr/local/bin/mc

COPY scripts/backup_exporter.py /exporter.py
RUN chmod +x /exporter.py
EXPOSE 8080

CMD ["python", "/exporter.py"]