FROM alpine:latest

RUN apk add --no-cache \
    postgresql-client \
    python3 \
    py3-pip \
    py3-faker \
    bash

COPY seeds/ /seeds/

COPY scripts/entrypoint-seeder.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]