{
 "title": "Patroni Cluster",
 "tags": [
  "patroni",
  "infrastructure"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Patroni roles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "patroni_primary", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "PostgreSQL Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "patroni_postgres_running", "legendFormat": "{{name}} database" }
   ]
  },
  {
   "title": "Etcd Availability",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(time() - patroni_dcs_last_seen <= bool 25)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Replication Status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "patroni_postgres_streaming", "legendFormat": "{{name}} replication" }
   ]
  },
  {
   "title": "HAProxy State",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "haproxy_backend_active_servers{proxy=\"postgres_servers\"}",
     "legendFormat": "Servers alive"
    }
   ]
  }
 ]
}